spring:
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false
  banner:
    location: banner.txt
test:
  rightAnswersCountToPass: 3
  locale: ru_RU
  fileNameByLocaleTag:
    ru_RU: questions_ru.csv
    en_US: questions.csv
